version: '3.8'
services:
  server:
    container_name: caddy
    image: "server:latest"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "5000:5000"
    volumes:
      - "./Caddyfile2:/etc/Caddyfile2"
      - "./caddy:/root/.caddy"
    links:
      - "api:api"
  api:
    container_name: api
    image: "api:latest"
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
